name: CI

on:
    pull_request:
    merge_group:
    push:
        branches:
            - develop
        tags:
            - '*'

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:

            -   name: Check out repository
                uses: actions/checkout@v6

            -   name: Set up Go
                uses: actions/setup-go@v4
                with:
                    go-version: '1.20'

            -   name: Build
                run: go build -v

            -   name: Test
                run: |
                    go test -coverprofile=./cov-report.out ./...
                    # go tool cover -html=cov-report.out -o coverage-report.html
                    go test -race -coverprofile=coverage.out -covermode=atomic

            -   name: Cache test coverage report
                uses: actions/cache@v3
                id: restore-test-coverage-report
                with:
                    path: ./cov-report.out
                    key: ${{ github.sha }}

    Static-Check:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Source
                uses: actions/checkout@v6

            -   name: Install Go
                uses: actions/setup-go@v3
                with:
                    go-version: 1.20.x

            # Generate mocks
            -   name: Generate mocks
                run: go generate ./...

            -   name: Static Code Analysis
                uses: golangci/golangci-lint-action@v3
                with:
                    skip-cache: true
                    skip-pkg-cache: true
                    skip-build-cache: true
                    args: |
                        --timeout 5m --out-${NO_FUTURE}format checkstyle:golangci-report.xml --issues-exit-code 0 --enable errcheck,gosimple,govet,ineffassign,staticcheck,typecheck,unused,gocritic,asasalint,asciicheck,errchkjson,copyloopvar,forcetypeassert,makezero,nilerr,unparam,unconvert,wastedassign,usestdlibvars
                    # --timeout 5m --out-format checkstyle:golangci-report.xml -issues-exit-code 0

            -   name: Cache golangci-lint report
                uses: actions/cache@v3
                id: restore-golangci-lint-report
                with:
                    path: ./golangci-report.xml
                    key: ${{ github.sha }}

    Go-Sec:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Source
                uses: actions/checkout@v6

            -   name: Install Go
                uses: actions/setup-go@v3
                with:
                    go-version: 1.20.x

            -   name: Run Gosec Security Scanner
                uses: securego/gosec@master
                with:
                    args: -no-fail -exclude-dir=\.*test\.* -fmt=sonarqube -out=./gosec-report.json -stdout ./...
                    # args: -exclude=G204,G301,G302,G304,G306 -exclude-dir=\.*test\.* ./...
                    # args: -no-fail -exclude-dir=\.*test\.* --verbose sonar -out=./gosec-report.json ./...

            -   name: Cache gosec report
                uses: actions/cache@v3
                id: restore-gosec-report
                with:
                    path: ./gosec-report.json
                    key: ${{ github.sha }}


    SonarCloud:
        runs-on: ubuntu-latest
        needs: [ Static-Check, Go-Sec, Build ]
        steps:
            -   name: Checkout Source
                uses: actions/checkout@v6

            -   name: Set up Go
                uses: actions/setup-go@v3
                with:
                    go-version: 1.20.x

            -   uses: actions/cache@v3
                id: restore-gosec-report
                with:
                    path: ./gosec-report.json
                    key: ${{ github.sha }}

            -   uses: actions/cache@v3
                id: restore-golangci-lint-report
                with:
                    path: ./golangci-report.xml
                    key: ${{ github.sha }}

            -   uses: actions/cache@v3
                id: restore-test-coverage-report
                with:
                    path: ./cov-report.out
                    key: ${{ github.sha }}

            -   name: SonarCloud Scan
                uses: SonarSource/sonarqube-scan-action@v5
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    Container:
        name: Build Container Image
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v6

            -   name: Write version vars
                id: version-vars
                run: |
                    BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
                    BRANCH=${GITHUB_REF_NAME#v}
                    APP_VERSION=$(cat config.json | jq -r ".version")
                    echo Version: $APP_VERSION
                    echo "VERSION=$APP_VERSION" >> $GITHUB_ENV
                    echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
                    echo "BUILD_DATE=$BUILD_DATE" >> $GITHUB_ENV

            -   name: Build Container Image
                id: build-image
                uses: docker/build-push-action@v7
                with:
                    push: false
                    tags: |
                        cloudtooling/s3bucket-exporter:next
                        cloudtooling/s3bucket-exporter:${{github.run_id }}
                        cloudtooling/s3bucket-exporter:${{env.APP_VERSION}}_rc
                    build-args: |
                        BUILD_DATE=${{env.BUILD_DATE}}
                        APP_VERSION=${{env.APP_VERSION}}

            -   name: Log in to GitHub container registry
                uses: docker/login-action@v4
                with:
                    username: ${{ vars.DOCKER_HUB_USER}}
                    password: ${{ secrets.DOCKER_HUB_TOKEN }}
                if: github.ref == 'refs/heads/develop'

            -   name: Deploy Container Image
                id: push-to-dockerhub-release
                run: |
                    docker push cloudtooling/s3bucket-exporter:next
                    docker push cloudtooling/s3bucket-exporter:${{env.APP_VERSION}}_rc
                if: github.ref == 'refs/heads/develop'

    CodeCov:
        runs-on: ubuntu-latest
        needs: [ Build ]
        steps:
            -   name: Checkout Source
                uses: actions/checkout@v6

            -   uses: actions/cache@v3
                id: restore-test-coverage-report
                with:
                    path: ./cov-report.out
                    key: ${{ github.sha }}

            -   name: Upload coverage reports to Codecov
                uses: codecov/codecov-action@v3
                with:
                    token: ${{ secrets.CODECOV_TOKEN }}
                    files: cov-report.out
                    flags: unittests
                    verbose: true

    LegalCheck:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout tree
                uses: actions/checkout@v6

            -   name: Run FOSSA scan and upload build data
                uses: fossa-contrib/fossa-action@v2
                with:
                    fossa-api-key: ${{ secrets.FOSSA_API_KEY }}

    Build-results:
        name: Build results
        if: ${{ always() }}
        runs-on: ubuntu-latest
        needs:
            - CodeCov
            - Go-Sec
            - Container
        steps:
            -   run: exit 1
                # see https://stackoverflow.com/a/67532120/4907315
                if: >-
                    ${{

                         contains(needs.*.result, 'failure')
                      || contains(needs.*.result, 'cancelled')
                      || contains(needs.*.result, 'skipped')
                      }}
